services:
  - type: private_service
    name: mysql
    env: docker
    plan: free
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_DATABASE
        value: student_db
      - key: MYSQL_USER
        value: vijit
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_ROOT_PASSWORD
        sync: false
